#!/usr/bin/env python3
"""Consumer-conformance gate (ADR-044): consumers declare what they read, this gate holds it.

Manifests in registry/consumers/*.yaml self-report each consumer's read surface — named
resource types (each with `noted_version`, the registry version the consumer was last verified
against) or `consumes_all_types: true` for envelope-level readers. Three invariants, every
state green or red:

  1. EXISTENCE — every named resource_type resolves in registry/resource-types/. A rename or
     removal that would break a declared consumer fails HERE, naming the consumer, instead of
     failing later in that consumer's runtime.
  2. VERSION HONESTY — every noted_version parses (X.Y.Z) and is not AHEAD of the registry's
     current version for that type. Ahead means the manifest claims verification against a
     registry that does not exist — the manifest lies; fail.
  3. FULL COVERAGE — every registry type is consumed by >=1 manifest (consumes_all_types
     counts) OR is explicitly acknowledged in registry/consumers/unconsumed.yaml. The gate
     REGENERATES the unconsumed set and compares (the check_type_standard.py ratchet
     discipline): a mismatch fails with the diff, so the acknowledgment file only ever changes
     as a conscious commit.

Manifest shape (per ADR-044): `consumer` (name/repo/description), exactly one of `consumes`
(list of {resource_type, noted_version, optional noted_digest — the sha256:<hex> content
digest of the revision last verified against, the exact half of the ADR-051 pin grammar})
or `consumes_all_types: true`, optional `schemas` (registry schema files read — must exist),
`coverage: declared|verified` (`verified` is the consumer's own promotion, never granted
here).

    python3 tests/check_consumer_conformance.py            # gate (CI)
    python3 tests/check_consumer_conformance.py --update   # rewrite unconsumed.yaml from the tree
"""
import glob
import json
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONSUMERS_DIR = os.path.join(ROOT, "registry", "consumers")
UNCONSUMED = os.path.join(CONSUMERS_DIR, "unconsumed.yaml")

SEMVER = re.compile(r"^\d+\.\d+\.\d+$")
DIGEST = re.compile(r"^sha256:[0-9a-f]{64}$")  # ADR-051 exact-pin form

UNCONSUMED_HEADER = """\
# Explicit acknowledgment of registry types no consumer manifest covers (ADR-044).
# GENERATED by tests/check_consumer_conformance.py --update; the gate regenerates the set and
# compares it against this file — any difference fails CI with the diff, so a type entering or
# leaving this list is always a conscious commit. A type living here is either ahead of its
# adopters or dead weight; both deserve a decision, not silence.
"""


def load_registry_versions():
    """resource_type -> current version, from the type specs."""
    versions = {}
    for path in sorted(glob.glob(os.path.join(ROOT, "registry", "resource-types", "**", "*"), recursive=True)):
        if not path.endswith((".json", ".yaml", ".yml")):
            continue
        with open(path, encoding="utf-8") as fh:
            doc = json.load(fh) if path.endswith(".json") else yaml.safe_load(fh)
        versions[doc["resource_type"]] = doc["version"]
    return versions


def parse_semver(s):
    return tuple(int(p) for p in s.split("."))


def load_manifests():
    manifests = []
    for path in sorted(glob.glob(os.path.join(CONSUMERS_DIR, "*.yaml"))):
        if os.path.abspath(path) == os.path.abspath(UNCONSUMED):
            continue
        with open(path, encoding="utf-8") as fh:
            manifests.append((os.path.relpath(path, ROOT), yaml.safe_load(fh)))
    return manifests


def check_manifest(rel, doc, versions, fails):
    """Structural + existence + version checks for one manifest. Returns its consumed set
    (None means consumes_all_types)."""
    if not isinstance(doc, dict):
        fails.append(f"{rel}: not a mapping")
        return set()
    consumer = doc.get("consumer")
    if not isinstance(consumer, dict) or not all(consumer.get(k) for k in ("name", "repo", "description")):
        fails.append(f"{rel}: `consumer` must carry name, repo, description")
    if doc.get("coverage") not in ("declared", "verified"):
        fails.append(f"{rel}: `coverage` must be declared|verified, got {doc.get('coverage')!r}")

    has_list = "consumes" in doc
    has_all = doc.get("consumes_all_types") is True
    if has_list == has_all:
        fails.append(f"{rel}: exactly one of `consumes` or `consumes_all_types: true` required")
        return set()

    for schema in doc.get("schemas") or []:
        if not os.path.exists(os.path.join(ROOT, schema)):
            fails.append(f"{rel}: declared schema file does not exist: {schema}")

    if has_all:
        return None

    consumed = set()
    for entry in doc.get("consumes") or []:
        rt, noted = entry.get("resource_type"), entry.get("noted_version")
        if rt not in versions:
            fails.append(f"{rel}: unknown resource_type {rt!r} — not in registry/resource-types/ "
                         f"(a rename/removal breaking this consumer, or a typo)")
            continue
        consumed.add(rt)
        if not (isinstance(noted, str) and SEMVER.match(noted)):
            fails.append(f"{rel}: {rt}: noted_version {noted!r} does not parse as X.Y.Z")
            continue
        if parse_semver(noted) > parse_semver(versions[rt]):
            fails.append(f"{rel}: {rt}: noted_version {noted} is AHEAD of the registry's {versions[rt]} "
                         f"— verification against a registry that does not exist")
        noted_digest = entry.get("noted_digest")
        if noted_digest is not None and not (isinstance(noted_digest, str) and DIGEST.match(noted_digest)):
            fails.append(f"{rel}: {rt}: noted_digest {noted_digest!r} does not parse as sha256:<64 hex> "
                         f"(the ADR-051 exact-pin form)")
    return consumed


def main() -> int:
    versions = load_registry_versions()
    manifests = load_manifests()
    fails = []

    consumed, any_all = set(), []
    for rel, doc in manifests:
        got = check_manifest(rel, doc, versions, fails)
        if got is None:
            any_all.append(doc["consumer"]["name"])
        else:
            consumed |= got

    named_only_unconsumed = sorted(set(versions) - consumed)
    computed = [] if any_all else named_only_unconsumed

    if "--update" in sys.argv:
        with open(UNCONSUMED, "w", encoding="utf-8") as fh:
            fh.write(UNCONSUMED_HEADER)
            yaml.safe_dump({"unconsumed": computed}, fh, default_flow_style=False)
        print(f"wrote {os.path.relpath(UNCONSUMED, ROOT)} ({len(computed)} type(s))")
        return 0

    if not os.path.exists(UNCONSUMED):
        fails.append(f"registry/consumers/unconsumed.yaml missing — run tests/check_consumer_conformance.py --update")
    else:
        with open(UNCONSUMED, encoding="utf-8") as fh:
            acked = (yaml.safe_load(fh) or {}).get("unconsumed") or []
        if sorted(acked) != computed:
            extra = sorted(set(acked) - set(computed))
            missing = sorted(set(computed) - set(acked))
            for t in missing:
                fails.append(f"unconsumed.yaml: {t} is consumed by no manifest but not acknowledged — "
                             f"add a consumer or acknowledge it (--update)")
            for t in extra:
                fails.append(f"unconsumed.yaml: {t} is acknowledged but now consumed (or gone) — "
                             f"stale entry; regenerate (--update)")

    n_named = sum(1 for _, d in manifests if isinstance(d, dict) and "consumes" in d)
    print(f"{len(manifests)} consumer manifest(s) ({n_named} named-surface, {len(any_all)} all-types: "
          f"{', '.join(any_all) or '-'}); {len(versions)} registry types; "
          f"{len(consumed)} named by >=1 consumer, {len(named_only_unconsumed)} named by none; "
          f"enforced unconsumed set: {len(computed)}")
    if fails:
        print(f"\nFAIL — {len(fails)} finding(s):")
        for f in fails:
            print(f"  {f}")
        return 1
    print("OK — every declared type exists, no version runs ahead, coverage acknowledged")
    return 0


if __name__ == "__main__":
    sys.exit(main())
